### ISSUE TITLE
RAL range

### ISSUE THREAD

**Issue by baldarn** [italiaremote/awesome-italia-remote#195]
**Describe the new feature you would like**
I would add a row with the range of RAL proposed for the jobs, if present

**Comment by ilmanzo** [comment]
You mean an overall range min-max for all the jobs in the same company, or an "average" range ? I guess it's very variable depending on position, role,  seniority, skills required, country ...

**Comment by edoardocostantinidev** [comment]
@baldarn as @ilmanzo suggested, we are not really showing single job positions, rather companies that hire remotely in italy, min-max range would be extremely wide and not very indicative. A company could have both junior and senior dev positions which probably have very different RALs. 

We could probably add a flag on/off for companies that show RAL in their job description, what do you think @alessandromr ?

**Comment by alessandromr** [comment]
Unfortunately adding other columns create some issue in the markdown visualisation so I'm not really into adding this.
Also with the EU Pay Transparency Directive salary should become more common if not the standard.
If we want to add the data without visualisation I'm totally ok with it.

**Comment by baldarn** [comment]
If the problem is the MD, we could remove the 'career page' and set that link in the name.
you can navigate to the main page from the career page ;)

so we will have the position for the compensation!
