### ISSUE TITLE
Stellantis

### ISSUE THREAD

**Issue by napolux** [italiaremote/awesome-italia-remote#237]
Cannot really find a remote job for stellantis added in https://github.com/italiaremote/awesome-italia-remote/pull/234

Should be removed IMHO, but I'd be glad to be proved wrong.

**Comment by edoardocostantinidev** [comment]
@napolux let's ping @antoniocali who added Stellantis in the first place.

**Comment by alessandromr** [comment]
@napolux  https://careers.fcagroup.com/job/15886681/ai-machine-learning-operations-engineer-remote/

**Comment by napolux** [comment]
@alessandromr remote us or worldwide?

**Comment by edoardocostantinidev** [comment]
@napolux I think it's either remote or US based, it's not very clear. they do mention the fact that their compensation package is specific to each country though so I'm leaning towards the fact that it is indeed remote.

**Comment by antoniocali** [comment]
It is remote. Sorry for late answer. I talked more and more times with some of HR US Based, and they always approve da fully remote job from europe
