### ISSUE TITLE
Add CODEOWNERS file.

### ISSUE THREAD

**Issue by edoardocostantinidev** [italiaremote/awesome-italia-remote#281]
We should add a `.github/CODEOWNERS` [file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) so that each PR is automatically assigned.

**Comment by alessandromr** [comment]
@edoardocostantinidev https://github.com/italiaremote/awesome-italia-remote/pull/282
