### ISSUE TITLE
Add Claranet Italy and remove Flowing from the list

### ISSUE THREAD

**Issue by ZarakiKanzaki** [italiaremote/awesome-italia-remote#306]
Hi! I wanted to suggest the inclusion of Claranet Italy, currently the company has acquired Flowing and the old xpeppers. The tech stack had also changed a lot through the last year.
If you need any further information don't hesitate to contact me.
Source: hired un flowing and now current employee in claranet Italy

**Comment by GuidoPenta** [comment]
There's already a PR opened to remove Flowing :)

**Comment by edoardocostantinidev** [comment]
#301 here's the relevant PR

**Comment by alessandromr** [comment]
PR is merged
