### ISSUE TITLE
Check the real possibility to work from Italy

### ISSUE THREAD

**Issue by mfirry** [italiaremote/awesome-italia-remote#345]
I was looking at [Hasura](https://hasura.io/careers/?jobId=vso4JFIiAd8G) and on their career page it simply says **_We hire across all states in the US. You can work remotely from anywhere in the US or in our office in San Francisco._**

**Comment by edoardocostantinidev** [comment]
Thanks for raising an issue @mfirry. I'll track down when it was added to see if it was made by an employee directly.

**Comment by edoardocostantinidev** [comment]
I see that @NoriSte added the company in #148, he was interviewed directly from them so unless the policy changed in the last year it should be good. I would say that unless someone has a newer interview with them stating they no longer hire in italy we can leave it. Happened quite a few times that hiring policies were not aligned on the career page of a company.

**Comment by mfirry** [comment]
Fair enough. It's just that if I go to a career page that states that, I would not apply. Anyhow, totally up to you to leave it there based on your info. Thanks.

**Comment by alessandromr** [comment]
From the career page, I see:
Our team is spread across 18 countries and we’re a remote workforce. For some of us who love working together in an office, or need to catch up for high-bandwidth discussions over a whiteboard and snacks, we have office spaces in SF and Bangalore!

And also:
We are a globally distributed team, with offices in San Francisco & Bangalore.

So it's also possible this is a requirement for a specific position

**Comment by NoriSte** [comment]
I was working there but now it's not the case. Anyway: even if they remain fully distributed, I also know they fired a lot of people and lot of them were European. I don't think they changed their policy but I just wanted you all to be aware of that.

**Comment by NoriSte** [comment]
One more thing: they NEVER publicly said that they hire remotely all over the world, even when they hired me from Italy.

**Comment by alessandromr** [comment]
Without more information I'm more for keeping the entry for now, feel free to add info if you have some
