### ISSUE TITLE
Link broken for "BOOM"

### ISSUE THREAD

**Issue by hpatoio** [italiaremote/awesome-italia-remote#363]
**Describe the bug**
Link for "Career Page" leads to error page for "BOOM".

**To Reproduce**
Click on "Career Page" on "Boom" row. Url is https://boom.co/careers

![image](https://github.com/italiaremote/awesome-italia-remote/assets/249948/8d9eff64-ad20-49cb-9d87-af26af4cb398)

**Comment by edoardocostantinidev** [comment]
@hpatoio let's see if tomorrow the site is still down, otherwise we'll contact the author of the PR that added that company to hear from him.

**Comment by edoardocostantinidev** [comment]
Hi @siasiboom, do you know if the company is still active? site is not working.

**Comment by alessandromr** [comment]
Removed
