### ISSUE TITLE
Consulting Company

### ISSUE THREAD

**Issue by rokity** [italiaremote/awesome-italia-remote#43]
**Describe the question**
What about add consulting companies that are currently working remotely or in smart working?

Which it'll be the tech stack used for this companies ?
 because there are different area, department ect ect 
 
 Thanks

**Comment by alessandromr** [comment]
Hi @rokity you can specify the main technologies that the company is using. With this setup unfortunately it's not possible to support a large number of tags.

**Comment by rokity** [comment]
I think it's better to leave the tech column empty , because there are too much department and section that it's difficult to track all the technologies used inside. I'm not so high in the company to track it, so I think it's better to leave empty if you approve.

**Comment by alessandromr** [comment]
Having empty columns it's not really helpful to people looking for a company with a specific tech stack, but feel free to add your company, maybe instead of the empty column you can repeat `Consulting`.

**Comment by rokity** [comment]
Consulting tag it's fine, thanks.
