### ISSUE TITLE
Add a parameter for Full remote/partial remote and show it on the table

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [italiaremote/awesome-italia-remote#52]
As a developer is very important for me to immediately know if a company allow full remote work or partial remote.
It could be helpful for developers that are looking for new job opportunities to have this information immediately visible on the table.

**Comment by alessandromr** [comment]
Hey, @andreaSimonePorceddu thanks for the suggestion. I think we can add a column for that, it's indeed a piece of good information to have.

**Comment by rokity** [comment]
About this argument I think it's relevant to know also where there are the offices of the company, so if someone wants to apply to this company can identify if it's near or far from your home if the company it' works in smart working.

So I suggest to add a column called "Office Locations".
