### ISSUE TITLE
Add link to each company's LinkedIn page

### ISSUE THREAD

**Issue by salvadorbs** [italiaremote/awesome-italia-remote#54]
As the title suggests. Maybe it is more useful to use the link to the company's job offers on LinkedIn, than the one on the LinkedIn company page.

**Comment by alessandromr** [comment]
Hey, @salvadorbs we don't force companies to put links to Linkedin, every company can add an URL to the main website and an URL to the career page (wherever it is hosted).

So if someone has added the Linkedin company page as a career page url then that's an error. 

I hope this answer your question

**Comment by salvadorbs** [comment]
Ok, I just saw that in addition to the career page, (from my personal experience) it is always convenient to see the page of job offers that are on LinkedIn of a certain company.

However, it was only a suggestion, so you can very well close the issue. Thank you. 😄
