### ISSUE TITLE
Allow multiple company type

### ISSUE THREAD

**Issue by lorthirk** [italiaremote/awesome-italia-remote#56]
I was going to submit data for my company, but I noticed that `type` is a `string`. In my case, our product targets both B2B and B2C, so I thought I should be allowed to enter both of them, ideally in an `array`.

What do you think?

**Comment by edoardocostantinidev** [comment]
If your company works on a product you can use the `Product` type.

**Comment by lorthirk** [comment]
I see. That was not highlighted in the CONTRIBUTING.md, so I missed that in the first place, but now I realize that this is the correct type.
