### ISSUE TITLE
Gitlab is not open for hiring in Italy

### ISSUE THREAD

**Issue by napolux** [italiaremote/awesome-italia-remote#6]
See **This table reflects the countries in which we have utilize PEO's but are currently NOT open for hiring:** section in https://about.gitlab.com/handbook/people-group/employment-solutions/#country-hiring-guidelines

**Comment by alessandromr** [comment]
Removed

**Comment by baldarn** [comment]
Now gitlab is open for hiring in Italy ;)

**Comment by naposysdig** [comment]
> Now gitlab is open for hiring in Italy ;)

Any source?

**Comment by baldarn** [comment]
> > Now gitlab is open for hiring in Italy ;)
> 
> Any source?

The link you provided :) search for Italy in the page

**Comment by naposysdig** [comment]
True, thanks!!
