### ISSUE TITLE
Add cognizant.com in the list looking for an Incident Manager 

### ISSUE THREAD

**Issue by icaman** [italiaremote/awesome-italia-remote#74]
Guideline for [CONTRIBUTING](https://github.com/italiaremote/awesome-italia-remote/blob/main/CONTRIBUTING.md#pull-requests)

https://www.linkedin.com/jobs/view/2918121287/?refId=VGChBerPRc2q7N7UQFC5zA%3D%3D

**Comment by alessandromr** [comment]
Hey @icaman, you can open a PR to add a new company. Read the https://github.com/italiaremote/awesome-italia-remote/blob/main/CONTRIBUTING.md for more info.
