### ISSUE TITLE
Split data.json / 1 json per company 

### ISSUE THREAD

**Issue by edoardocostantinidev** [italiaremote/awesome-italia-remote#8]
Given the growing number of companies inside `data.json` I propose to split them following this logic:
For each company there is a single json file located in a subfolder `companies`. 
This would improve contributing to the repo.

I can take care of this fix if you agree @alessandromr.

**Comment by FabrizioCafolla** [comment]
Great!

Once separated into multiple files you need to create a validator (perhaps with [json-schema](https://json-schema.org/)) so you can test the pr and automatically decline in case of incorrect data 

Do you think you can implement this feature: split + validator?

Or separate into two separate issues?

**Comment by edoardocostantinidev** [comment]
> Great!
> 
> Once separated in multiple files it is necessary to create a validator (maybe with [json-schema](https://json-schema.org/)) so we can test the pr and reject automatically in case of wrong data
> 
> Do you think you can implement this feature: split + validator?
> 
> Or separate into two issues?

Yes seems fair to add some tests with this refactor, I'll take care of it 👍🏻

**Comment by FabrizioCafolla** [comment]
This is the json-schema that replicates the current structure:
```
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
      
    "properties": {
      	"name": {
        	"type": "string",
        	"description": "Comapny name"
      	},
          
    	"url": {
    		"type": "string",
    		"format": "uri",
    		"pattern": "^(https?)://",
            "description": "URL Comapny site"
		},
          
      	"career_page_url": {
    		"type": "string",
    		"format": "uri",
    		"pattern": "^(https?)://",
            "description": "URL Comapny career page"

		},
          
        "type": {
    		"type": ["string", "array"],
        	"enum": ["product", "consulting"],
            "description": "Type of services offered by the company"
        },
          
      	"tags": {
          "type": "array",
          "description": "Technology used"
        }
    },
    
    "additionalProperties": false,
    
    "required": ["name", "url", "career_page_url", "type", "tags"]
}
```

Example json:

```
{
    "name": "test",
    "url": "https://test.com",
    "career_page_url": "https://test",
    "type": "product",
    "tags": ["aws"]
}
```

@alessandromr I think it is appropriate to add to "type" values such as: B2C, D2C B2B etc..

**Comment by edoardocostantinidev** [comment]
I think it's best if we open another issue to discuss json schema as it probably also needs a template change @FabrizioCafolla @alessandromr .

**Comment by edoardocostantinidev** [comment]
I also think it's a good idea to add the validator step inside the PR flow so we avoid to bring a non working status to main branch. aka merge only if it compiles.

**Comment by alessandromr** [comment]
Closed with https://github.com/italiaremote/awesome-italia-remote/pull/16
I will open another PR for validation during pull request workflow

**Comment by brucellino** [comment]
I came here looking for the JSON schema... I was going to suggest adding a pre-commit hook to perform the schema validation, but it seems you guys are doing this with a small go program. What's the current approach?

**Comment by edoardocostantinidev** [comment]
@brucellino as of right now we just run a GHA that checks and validates the json. No schema involved everything is pretty basic. We are also thinking about auto-generating PRs #327
