### ISSUE TITLE
[Enhancement] Remote tags

### ISSUE THREAD

**Issue by elgorditosalsero** [italiaremote/awesome-italia-remote#83]
The current `tags` are `FullRemote` and `Mixed`.

I think would be better to rename `FullRemote` to `Full` as the column name is `Remote Policy`

> I put the label in the title as I can't add them

**Comment by elgorditosalsero** [comment]
> I think about FullRemote for companies without an office where every employee (at least in the category) are working remotely. Instead mixed when only some employees work remotely.

@alessandromr quoting you from #82 

So, `Full` would be for companies without physical office and `Mixed` for companies with, at least, 1 office?

**Comment by alessandromr** [comment]
I see that my idea probably works only in my head, maybe we should stick to `Full` and `Partial`, where `Partial` means some days remote and some days in the office. 
Feel free to suggest something else

**Comment by elgorditosalsero** [comment]
I would propose:

| Label | Meaning |
| ----- | --------- |
| `Full` | Company doesn't have physical offices, so you'll always work remotely |
| `Hybrid` | Company allows remote but only for some days |
| `Optional` | Company allows you to choose when work remotely or in office, but can ask you to go sometimes |

I think a table like this one as Legenda could be nice

**Comment by alessandromr** [comment]
Fixed with https://github.com/italiaremote/awesome-italia-remote/commit/90532723dd683680fd8d21558db91695230749e4 and https://github.com/italiaremote/awesome-italia-remote/commit/3c93f6ec9aceeb19284b2b7c4056f668debe2ab4
