### ISSUE TITLE
TLM Partners isn't shown in the README.md

### ISSUE THREAD

**Issue by andreabar** [italiaremote/awesome-italia-remote#95]
I added my remote company two days ago, adding tlm_partners.json inside the data folder, however it's not visibile yet in the readme file.

**Comment by alessandromr** [comment]
Hey @andreabar, thanks for reporting this, during the PR i missed the detail that you have created another category "videogames" for it.
So if you agree I will move it back to "cloud_software" so it will show and then in a future PR we will implement a parameter that show the industry, like crypto, videogames, ecc..

**Comment by andreabar** [comment]
> Hey @andreabar, thanks for reporting this, during the PR i missed the detail that you have created another category "videogames" for it.
> So if you agree I will move it back to "cloud_software" so it will show and then in a future PR we will implement a parameter that show the industry, like crypto, videogames, ecc..

Yes, I'm totally okay with that. Thank you

**Comment by alessandromr** [comment]
Fixed with https://github.com/italiaremote/awesome-italia-remote/commit/dbacc00a79517161e629c87fce920ef4032212d6
